# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests 
      run: cargo test --verbose 
    - name: Clippy (clippy::pedantic)
      run: cargo clippy -- -W clippy::pedantic
    - name: Clippy (clippy::all)
      run: cargo clippy -- -W clippy::all

